Classification resnet add dump
MegEngine/Models pull request #109
Opened 2021-09-14 10:15 UTC by tpoisonooo

增加 resetnet18 dump 成 .mge 的代码

2021-09-14 10:27 UTC, wjfwzzc requested changes

2021-09-14 10:27 UTC, wjfwzzc commented on official/vision/classification/resnet/dump.py
> +    model = resnet_model.__dict__['resnet18'](pretrained=True)
既然是进入公开库，最好是允许传参数，目前写死的`resnet18`不太好……而且感觉这个tool原则上shufflenet什么的都可以用？

2021-09-14 10:27 UTC, wjfwzzc commented on official/vision/classification/resnet/dump.py
> +    dump_static_graph(model)
`graph_name`也给个args比较好

2021-09-14 10:27 UTC, wjfwzzc commented on official/vision/classification/resnet/dump.py
> +    data = mge.Tensor(np.random.random((1, 3, 224, 224)))
其实shape也是传个参数比较好吧……用户也不是都用224

2021-09-14 10:46 UTC, wjfwzzc commented on official/vision/classification/resnet/dump.py
> +# pylint: disable=import-error
呃……不要通过这种关掉检查的方式偷家……

2021-09-14 10:48 UTC, tpoisonooo commented on official/vision/classification/resnet/dump.py
> +# pylint: disable=import-error
你的代码就是这么写的啊...

2021-09-14 10:49 UTC, tpoisonooo commented on official/vision/classification/resnet/dump.py
> +# pylint: disable=import-error
我哪里会，都是从 models 里现学的。

2021-09-14 10:51 UTC, tpoisonooo commented
```bash
✗ python3 dump.py --help
usage: dump.py [-h] [-a ARCH] [-s SHAPE [SHAPE ...]] [-o OUTPUT]

MegEngine Classification Dump .mge

optional arguments:
  -h, --help            show this help message and exit
  -a ARCH, --arch ARCH  model architecture (default: resnet18)
  -s SHAPE [SHAPE ...], --shape SHAPE [SHAPE ...]
                        input shape (default: 1 3 224 224)
  -o OUTPUT, --output OUTPUT
                        output filename
```

2021-09-14 11:04 UTC, wjfwzzc commented on official/vision/classification/dump.py
> +        nargs="+",
看起来这个参数固定消耗4个参数，`nargs=4`

2021-09-14 11:05 UTC, wjfwzzc commented on official/vision/classification/dump.py
> +import shufflenet.model as snet_model
CI挂在该行末有空格

2021-09-14 12:31 UTC, wjfwzzc requested changes

2021-09-14 12:31 UTC, wjfwzzc commented on official/vision/classification/dump.py
> +        nargs="4",
你要按照我说的改呀……是`=4`不是`="4"`
改完要跑一遍试试呀……

2021-09-14 12:31 UTC, wjfwzzc commented on official/vision/classification/dump.py
> +import resnet.model as resnet_model
既然说留了，怎么又把`# pylint: disable=import-error`删了……

2021-09-14 12:31 UTC, wjfwzzc commented on official/vision/classification/dump.py
> +        model = resnet_model.__dict__[args.arch](pretrained=True)
`model = getattr(resnet_model, args.arch)(pretrained=True)`

2021-09-14 12:31 UTC, wjfwzzc commented on official/vision/classification/dump.py
> +        model = snet_model.__name__[args.arch](pretrained=True)
`model = getattr(snet_model, args.arch)(pretrained=True)`

2021-09-15 03:14 UTC, tpoisonooo commented
嗯，多 PR 两次就会了...

2021-09-16 07:42 UTC, wjfwzzc requested changes

2021-09-16 07:42 UTC, wjfwzzc commented on official/vision/classification/dump.py
> +import sys
请用如下替换，可以过CI
```python
import argparse
import sys

import resnet.model as resnet_model  # pylint: disable=import-error
import shufflenet.model as snet_model  # pylint: disable=import-error

import numpy as np

import megengine as mge
from megengine import jit
```

2021-09-16 07:42 UTC, wjfwzzc commented on official/vision/classification/dump.py
> +
函数前2个空行

2021-09-16 07:42 UTC, wjfwzzc commented on official/vision/classification/dump.py
> +
函数前2个空行

2021-09-16 07:42 UTC, wjfwzzc commented on official/vision/classification/dump.py
> +
2个空行

2021-09-17 06:36 UTC, wjfwzzc approved these changes

2021-09-17 06:37 UTC, closed without merging