Add new keypoint models
MegEngine/Models pull request #60
Opened 2020-08-28 12:16 UTC by greatlog

Add HRnets, and RSNs.

2020-09-02 09:31 UTC, wjfwzzc commented
此PR改为WIP，理由如下：
1. MegEngine 1.0临近，会有breaking changes
2. 与内部版本的点还对不齐，且大致定位到框架本身的diff，可能需要引入相关人员再看看

2020-11-21 08:49 UTC, wjfwzzc requested changes

2020-11-21 08:49 UTC, wjfwzzc commented on official/vision/keypoints/README.md
> +- [Learning Delicate Local Representations for Multi-Person Pose Estimation](https://arxiv.org/pdf/2003.04030.pdf) Yuanhao Cai, Zhicheng Wang, Zhengxiong Luo, Binyi Yin, Angang Du, Haoqian Wang, Xian
引用格式不太正规，仿照<https://github.com/MegEngine/Models/tree/master/official/vision/detection>搞一下？

最好留abs链接，有的人不想直接下载pdf。

2020-11-21 08:49 UTC, wjfwzzc commented on official/vision/keypoints/train.py
> +    # @jit.trace(symbolic=True, opt_level=2)
目前trace不完善，我们统一不出现所有trace，包括注释

2020-11-21 08:49 UTC, wjfwzzc commented on official/vision/keypoints/train.py
> +            callbacks=[dist.make_allreduce_cb("SUM", dist.WORLD)],
如果用SUM，则world_size要乘在weight_decay而非lr上（具体原因与等效学习率和dist sgd实现有关），否则用MEAN。

经过前期的一些讨论，我们在Models中统一用SUM。所以78/119行的行为需要改动。

2020-11-21 08:49 UTC, wjfwzzc commented on README.md
> +| MSPN_4stage |MSPN     |256x192| 0.752 | 0.900 | 0.819 | 0.716 | 0.825 | 0.819 | 0.943 | 0.875 | 0.770 | 0.887 |
旧的weights都能用么？需要重新训练并更新weights么（尤其是我看很多训练参数已经变了）？

之前点对不上内部版本的问题有进展么？如果有的话是否一并修复？

2020-11-21 08:49 UTC, wjfwzzc commented on official/vision/keypoints/models/danet.py
> +    "https://data.megengine.org.cn/models/weights/keypoint_models/danet72_256x192_69_8.pkl"
weights文件名中应当包含该文件的md5（前6/8位即可），命名规则具体可参照detection；这是为了让hub和用户能从文件名感知到权重的更新。

2020-11-21 08:49 UTC, wjfwzzc commented on official/vision/keypoints/models/hrnet.py
> +class Make_One_Branch(M.Module):
类名一般采用驼峰格式，没有下划线；下同

2020-11-21 08:49 UTC, wjfwzzc commented on official/vision/keypoints/models/hrnet.py
> +        super(Make_One_Branch, self).__init__()
python3中直接写`super().__init__()`即可，下同

2020-11-21 08:49 UTC, wjfwzzc commented on official/vision/keypoints/models/mspn.py
> +            tmp = ((stage_out[-1] - heatmaps[:, -1]) ** 2).mean(3).mean(2) * (
我们的mean好像支持传多个维度了，如`.mean([2,3])`

2020-11-26 02:59 UTC, greatlog commented on README.md
> +| MSPN_4stage |MSPN     |256x192| 0.752 | 0.900 | 0.819 | 0.716 | 0.825 | 0.819 | 0.943 | 0.875 | 0.770 | 0.887 |
旧的weigts能用。和内部版本对不上的问题仍旧没有解决。考虑到1.0的更新，可以再对一次。

2020-11-26 03:00 UTC, greatlog commented on official/vision/keypoints/models/danet.py
> +    "https://data.megengine.org.cn/models/weights/keypoint_models/danet72_256x192_69_8.pkl"
原来是按cocoval上的AP来命名的，后面对点的新模型会按照统一格式命名。

2020-11-27 05:35 UTC, wjfwzzc commented on official/vision/keypoints/config.py
> +    heat_kernel = [k * 4 for k in heat_kernel]
merge一下吧。
`heat_kernel = [k * 4 for k in [2.6, 2.0, 1.7, 1.4]]`

2020-11-27 05:35 UTC, wjfwzzc commented on official/vision/keypoints/config.py
> +    # augumentatio
typo: `augmentation`

2020-11-27 05:35 UTC, wjfwzzc commented on official/vision/keypoints/inference.py
> +        keep = py_cpu_nms(persons, 0.7)
考虑把`0.7`变成超参？

2020-11-27 05:35 UTC, wjfwzzc commented on official/vision/keypoints/models/hrnet.py
> +        self.transistion1 = M.Sequential(
typo: `transition`
需要修改weights

2020-11-27 05:35 UTC, wjfwzzc commented on official/vision/keypoints/models/mspn.py
> +        super().__init__()
这个`ResnetBody`和标准`ResNet`的区别是什么？
可不可以像det和seg一样直接复用？

2020-11-27 05:35 UTC, wjfwzzc commented on official/vision/keypoints/train.py
> +            model.parameters(requires_grad=True),
`requires_grad=True`的写法已经不生效了。现在需要手动把freeze的层提前filter掉，包括optimizer也是如此。见如下代码：
<https://github.com/MegEngine/Models/blob/dc2f2cfb228a135747d083517b98aea56e7aab92/official/vision/detection/tools/train.py#L107-L129>

2020-11-27 06:04 UTC, greatlog commented on official/vision/keypoints/train.py
> +            model.parameters(requires_grad=True),
其实我的模型里没有需要freeze的地方，所以这里直接去掉```bash requires_grad=True``` 了

2020-11-27 06:06 UTC, greatlog commented on official/vision/keypoints/models/mspn.py
> +        super().__init__()
这里之前好像讨论过，是不能复用的。这个body是不好前两层的，只有四个stage，我需要反复调用这个，所以重定义了一个。

2020-11-27 06:07 UTC, greatlog commented on official/vision/keypoints/models/hrnet.py
> +        self.transistion1 = M.Sequential(
这个模型还在1.1上对点，后续会一并修改

2020-11-30 14:57 UTC, wjfwzzc commented on official/vision/keypoints/models/mspn.py
> +        super().__init__()
哦哦对= =在构造函数开头加个注释说明一下吧……

2020-12-03 07:38 UTC, wjfwzzc commented on official/vision/keypoints/train.py
>  import official.vision.keypoints.models as M
不建议采用缩写`M`，因为基本上是被`megengine.module`占用了。
叫`kp`？`kpm`？哪怕长一点叫`models`也ok吧……
`test.py`, `inference.py`同理。

2020-12-03 07:38 UTC, wjfwzzc commented on official/vision/keypoints/models/hrnet.py
> +            outs.append(F.nn.interpolate(out, scale_factor=2 ** i, align_corners=True))
重点疑似：`align_corners=True`

2020-12-03 07:38 UTC, wjfwzzc commented on official/vision/keypoints/models/mspn.py
> +                    out, scale_factor=2 ** (3 - j), align_corners=True
重点疑似：`align_corners=True`

2020-12-03 07:38 UTC, wjfwzzc commented on official/vision/keypoints/models/hrnet.py
> +                    up = F.nn.interpolate(up, [x[i].shape[2], x[i].shape[3]])
可直接写成：`F.nn.interpolate(up, x[i].shape[2:])`

2020-12-03 07:38 UTC, wjfwzzc commented on official/vision/keypoints/models/mspn.py
> +        outs = self.forward(images)
无论在PyTorch还是MegEngine中，`out = model.forward(x)`都是一个不提倡的写法。
因为`out = model(x)`不仅仅调用了`forward`，还可能调用一些hook。
推荐改法一：`outs = self(images)`
推荐改法二：`calc_loss`的参数直接传入outs，在`train.py`调用`outs = model(x), model.calc_loss(outs, y, mask)`

`predict`函数同理。
所有模型都需要检查一遍。

2021-01-08 05:51 UTC, wjfwzzc commented on official/vision/keypoints/config.py
> +    img_std = [255 * m for m in [0.225, 0.229, 0.224]]
好像不对啊……你这个顺序既不是RGB也不是BGR，而是BRG？
以及这里是不是会影响旧weights的点？

2021-01-18 06:58 UTC, wjfwzzc commented on official/vision/keypoints/models/simplebaseline.py
> +       simplebaseline_res101_256x192_0to255_71dot8_df6304.pkl"
res101?
0to255是啥意思……

2021-01-18 06:58 UTC, wjfwzzc commented on official/vision/keypoints/models/simplebaseline.py
> +        simplebaseline152_256x192_0_255_72_4.pkl"
不要这样折行，直接
"https://xxx/aaa/bbb"
"ccc.pkl"
即可

2021-01-18 06:58 UTC, wjfwzzc commented on official/vision/keypoints/train.py
> +mge.device.set_prealloc_config(1024, 1024, 512 * 1024 * 1024, 2.0)
这句可以删掉了

2021-01-18 07:05 UTC, greatlog commented on official/vision/keypoints/models/simplebaseline.py
> +       simplebaseline_res101_256x192_0to255_71dot8_df6304.pkl"
0to255说的是heatmap的取值范围是0~255...

2021-01-18 07:15 UTC, wjfwzzc approved these changes

2021-01-18 07:18 UTC, merged