feat(detection): dynamic batch size for tracing
MegEngine/Models pull request #67
Opened 2020-10-09 08:21 UTC by wjfwzzc

2020-10-13 11:46 UTC, FateScript commented on official/vision/detection/layers/det/rpn.py
>              nms_keep_inds = nms_keep_inds[:min(post_nms_top_n, nms_keep_inds.shape[0])]
有了post_nms_top_n ，这一行可以删掉了

2020-10-13 11:49 UTC, FateScript commented on official/vision/detection/models/atss.py
> +            ).sum() / F.maximum(sum_ctr, 1e-5) * self.cfg.loss_bbox_weight
极端情况下sum_ctr = 0的时候不会导致超大的loss吗

2020-10-13 11:52 UTC, FateScript commented on official/vision/detection/models/fcos.py
> +            ).sum() / F.maximum(sum_ctr, 1e-5) * self.cfg.loss_bbox_weight
ditto

2020-10-13 12:00 UTC, FateScript commented on official/vision/detection/tools/test_random.py
> -import importlib
test_random和train_random还要留着吗？

2020-10-13 12:04 UTC, FateScript requested changes
PTAL.

2020-10-13 12:52 UTC, wjfwzzc commented on official/vision/detection/models/atss.py
> +            ).sum() / F.maximum(sum_ctr, 1e-5) * self.cfg.loss_bbox_weight
不会，因为这同时意味着上面乘的`gt_ctrness[fg_mask]`很小。`1e-5`只有防止除零的用处。

2020-10-13 12:53 UTC, wjfwzzc commented on official/vision/detection/tools/test_random.py
> -import importlib
按理说不用了……包括`PseudoDetectionDataset`。但是engine组未来仍然会（长期）需要用它，比如调trace调性能之类的，总得有个地方放才好……

2020-10-13 12:56 UTC, wjfwzzc commented on official/vision/detection/layers/det/rpn.py
>              nms_keep_inds = nms_keep_inds[:min(post_nms_top_n, nms_keep_inds.shape[0])]
done

2020-10-14 06:33 UTC, FateScript reviewed
LGTM.

2020-10-14 06:34 UTC, FateScript approved these changes

2020-10-14 06:35 UTC, merged