imperative-runtime code of Faster R-CNN
MegEngine/Models pull request #68
Opened 2020-10-09 12:28 UTC by FateScript

2020-10-09 13:26 UTC, wjfwzzc requested changes

2020-10-09 13:26 UTC, wjfwzzc commented on official/vision/detection/layers/det/sampling.py
> +def sample_mask_from_labels(labels, num_sample, sample_value):
似乎返回值可以是bool了。

2020-10-09 13:26 UTC, wjfwzzc commented on official/vision/detection/models/faster_rcnn.py
> +        #         p.requires_grad = False
直接删掉吧

2020-10-09 13:26 UTC, wjfwzzc commented on official/vision/detection/tools/train.py
> +        model.backbone.bottom_up.load_state_dict(weights, strict=False)
为什么要`strict=False`？（如果我们不打算支持传backbone weights的话）

2020-10-09 13:26 UTC, wjfwzzc commented on official/vision/detection/models/faster_rcnn.py
> +        return layers.get_padded_tensor(normed_image, 32, 0.0)
这里确定要修回来么？

2020-10-10 02:37 UTC, FateScript commented on official/vision/detection/layers/det/pooler.py
> +        level_rois = rois[inds]
inds_list里会用到这些下标，所以对于cond_take，只能等nonzeros

2020-10-10 02:38 UTC, FateScript commented on official/vision/detection/layers/det/pooler.py
>      level_assignments = F.floor(
叫assign_level?

2020-10-10 02:56 UTC, FateScript commented on official/vision/detection/layers/det/pooler.py
>      level_assignments = F.floor(
我改成assigned_level了

2020-10-10 03:27 UTC, FateScript commented on official/vision/detection/layers/det/sampling.py
> +def sample_mask_from_labels(labels, num_sample, sample_value):
试了一下，bool类型的赋值有点问题，打了个TODO tag

2020-10-10 03:27 UTC, FateScript commented on official/vision/detection/tools/train.py
> +        model.backbone.bottom_up.load_state_dict(weights, strict=False)
因为正常hub里的res50有fc，载入会报错

2020-10-10 05:19 UTC, wjfwzzc commented on official/vision/detection/tools/train.py
> +        model.backbone.bottom_up.load_state_dict(weights, strict=False)
again，**如果我们不打算支持传backbone weights的话**

2020-10-10 05:27 UTC, wjfwzzc reviewed
另外上面还有一些没有修，github会折叠一部分reviews，别漏了。

2020-10-10 05:27 UTC, wjfwzzc commented on official/vision/detection/layers/det/rcnn.py
> +            all_rois = F.concat([rpn_rois[batch_roi_mask == 1], gt_rois])
`all_rois = F.concat([rpn_rois[batch_roi_mask], gt_rois])`

2020-10-10 05:27 UTC, wjfwzzc commented on official/vision/detection/layers/det/rpn.py
> +            ).sum(axis=1) * fg_mask).sum() / F.maximum(num_samples, 1.0)
`fg_mask = rpn_labels > 0`
`smooth_l1_loss(pred_bbox_offsets[fg_mask], rpn_bbox_targets[fg_mask], rpn_labels[fg_mask], ...)`

2020-10-10 05:31 UTC, wjfwzzc commented on official/vision/detection/layers/det/sampling.py
> +    _, mask_inds = F.cond_take(labels == label_value, labels)
包括L26-29

2020-10-10 07:17 UTC, FateScript commented on official/vision/detection/layers/det/rcnn.py
>              keep_mask = fg_inds_mask + bg_inds_mask
因为sample_mask_from_labels返回的并不是bool tensor，这个需要engine修了bool tensor的getitem之后修复了

2020-10-10 07:47 UTC, FateScript commented on official/vision/detection/layers/det/sampling.py
> +    topk_tensor = F.zeros_like(labels).astype("float32")
zeros_like里并没有dtype

2020-10-10 08:38 UTC, FateScript commented on official/vision/detection/tools/train.py
> +        model.backbone.bottom_up.load_state_dict(weights, strict=False)
当然可以，但是支持这个功能不是更科学吗

2020-10-10 09:15 UTC, wjfwzzc commented on official/vision/detection/layers/det/sampling.py
> +    topk_tensor = F.zeros_like(labels).astype("float32")
好吧= =

2020-10-10 09:15 UTC, wjfwzzc commented on official/vision/detection/tools/train.py
> +        model.backbone.bottom_up.load_state_dict(weights, strict=False)
先留着吧……

2020-10-10 09:20 UTC, wjfwzzc approved these changes

2020-10-10 09:20 UTC, wjfwzzc commented
LGTM.

2020-10-10 09:20 UTC, merged