WIP: feat(segmentation): migrate to functional api 1.0
MegEngine/Models pull request #69
Opened 2020-10-14 06:50 UTC by wjfwzzc

1. reformat according to detection
2. support functinal api 1.0
3. support multi-gpu testing
4. update new model weights

2020-10-15 11:25 UTC, FateScript commented on official/vision/segmentation/models/deeplabv3plus.py
> +            M.Conv2d(256, 48, 1, 1, padding=1 // 2, bias=False),
这个bias之前没发现？

2020-10-15 11:25 UTC, FateScript commented on official/vision/segmentation/models/deeplabv3plus.py
> +            M.Conv2d(256, 48, 1, 1, padding=1 // 2, bias=False),
而且下面很多bias改了

2020-10-15 11:30 UTC, FateScript commented on official/vision/segmentation/tools/test.py
> +def pad_image_to_shape(img, shape, border_mode, value):
我们的transform里面不是也有pad

2020-10-15 11:30 UTC, wjfwzzc commented on official/vision/segmentation/models/deeplabv3plus.py
> +            M.Conv2d(256, 48, 1, 1, padding=1 // 2, bias=False),
对，这些去掉bias是因为后面有BN。

2020-10-15 11:42 UTC, FateScript commented on official/vision/segmentation/tools/utils.py
> +        self.sum = [0 for i in range(self.record_len)]
self.reset()

2020-10-15 11:43 UTC, FateScript requested changes
PTAL @wjfwzzc

2020-10-18 10:25 UTC, wjfwzzc commented on official/vision/segmentation/tools/utils.py
> +        self.sum = [0 for i in range(self.record_len)]
done

2020-10-19 02:22 UTC, FateScript reviewed
LGTM.

2020-10-19 02:22 UTC, FateScript approved these changes

2020-10-19 02:22 UTC, merged