Update classification codebase to 1.0
MegEngine/Models pull request #71
Opened 2020-10-15 10:27 UTC by zhouyizhuang-megvii

2020-10-15 11:28 UTC, wjfwzzc commented on official/vision/classification/resnet/model.py
> +        super(BasicBlock, self).__init__()
python3不再需要`super(..., self)`了，`super()`即可

2020-10-15 11:28 UTC, wjfwzzc commented on official/vision/classification/resnet/test.py
> +class AverageMeter(object):
python3默认就是新式类，不再需要`class A(object):`了，只需要`class A:`

2020-10-15 11:29 UTC, wjfwzzc commented
别忘把pylint修了。

2020-10-19 04:11 UTC, wjfwzzc requested changes
README没更新，尤其是很多参数已经变了。
另外代码似乎是多机全占的逻辑，明确不支持单机单/多卡了是么？

2020-10-19 04:11 UTC, wjfwzzc commented on official/vision/classification/resnet/inference.py
> +    model = resnet_model.__dict__[args.arch](pretrained=(args.model is None))
感觉`getattr`比`__dict__`还是更好一些？改过来的理由是？

2020-10-19 05:15 UTC, zhouyizhuang-megvii commented on official/vision/classification/resnet/inference.py
> +    model = resnet_model.__dict__[args.arch](pretrained=(args.model is None))
我一直是习惯`__dict__`的，另外[torch](https://github.com/pytorch/examples/blob/master/imagenet/main.py#L134)也是这么写的

2020-10-19 05:35 UTC, zhouyizhuang-megvii commented
> 另外代码似乎是多机全占的逻辑，明确不支持单机单/多卡了是么？

现在支持`--ngpus`参数了，README也更新好了

2020-10-19 10:28 UTC, wjfwzzc commented
还差一点点，当`world_size = 1 and ngpus = 1`时，`init_process_group`是否有不work的可能？
还有其它dist的环节可能都需要check，比如`bcast_list_`和`all_reduce_sum`。
建议真实跑起来看看吧……

2020-10-19 12:03 UTC, zhouyizhuang-megvii commented
> 还差一点点，当`world_size = 1 & ngpus = 1`时，`init_process_group`是否有不work的可能？
> 如果不work要加特判的话，还有其它dist的环节可能都需要check，比如`gm`的callback，`bcast_list_`和`all_reduce_sum`。
> 建议真实跑起来看看吧……
> 
> 还有，默认`dist.make_allreduce_cb("MEAN")`，不`SUM`了？

单卡的场景可以正常跑了；也已修改为`SUM`

2020-10-19 12:17 UTC, wjfwzzc approved these changes
LGTM.

2020-10-19 12:18 UTC, merged