feat(detection): add free_anchor
MegEngine/Models pull request #82
Opened 2020-11-19 09:21 UTC by FateScript

please kindly review @wjfwzzc

2020-11-20 06:19 UTC, wjfwzzc requested changes
others：
1. `hubconf.py`没有更新。此外hub那边也应该有对应PR。
2. 点（相比于同repo其它模型）略低，需要在新训练条件下更新weights。
3. 缺少大模型。

2020-11-20 06:19 UTC, wjfwzzc commented on official/vision/detection/models/free_anchor.py
> +                gt_pred_prob[0, 0] = 0.001
这类哨兵目前依然干不掉是么？基于v1.1.0，是因为具体哪个（些）环节依然不支持？
在可以预见的将来能干掉么？比如v1.2.0？

2020-11-20 06:19 UTC, wjfwzzc commented on official/vision/detection/models/free_anchor.py
> +            matched_score = F.gather(gather_src, 2, gather_idx)
似乎可以用`F.indexing_one_hot`来实现？（速度更快，避免squeeze等）

2020-11-20 06:19 UTC, wjfwzzc commented on official/vision/detection/models/free_anchor.py
> +        self.train_image_short_size = 800
强烈建议与其它方法对齐训练条件，比如采用ms training。

2020-11-20 06:19 UTC, wjfwzzc commented on official/vision/detection/models/free_anchor.py
> +        # self.match_allow_low_quality = True
删掉

2020-11-20 06:19 UTC, wjfwzzc commented on official/vision/detection/models/free_anchor.py
> +        # self.reg_loss_weight = 1.0
删掉

2020-11-20 06:19 UTC, wjfwzzc commented on official/vision/detection/models/free_anchor.py
> +        self.smooth_l1_beta = 0.1  # use L1 loss when beta = 0
这里我倒是觉得可以统一用0。应该也会涨点。

2020-11-20 06:19 UTC, wjfwzzc commented on official/vision/detection/models/free_anchor.py
> +class FreeAnchorConfig:
建议和当前的`RetinaNetConfig`逐行diff一下，好像缺了点几条，比如`in_features`。

2020-11-20 06:50 UTC, wjfwzzc commented on official/vision/detection/layers/basic/functional.py
> +        eps = np.finfo(x.dtype).tiny
似乎用`np.finfo(x.dtype).eps`更好一些

2020-11-23 02:41 UTC, FateScript commented on official/vision/detection/models/free_anchor.py
> +                gt_pred_prob[0, 0] = 0.001
这个是因为空tensor的问题，gt_pred_prob不能是全0的，所以有这个work around，除非空tensor可以支持

2020-11-23 06:15 UTC, wjfwzzc commented on official/vision/detection/models/free_anchor.py
> +                gt_pred_prob[0, 0] = 0.001
不够具体。具体是哪一行，哪个op不支持空tensor？

2020-11-23 06:56 UTC, FateScript commented on official/vision/detection/models/free_anchor.py
> +                gt_pred_prob[0, 0] = 0.001
[这一行](https://github.com/MegEngine/Models/blob/44e786bf2326a1422b1c03a1158f329062c4d809/official/vision/detection/models/free_anchor.py#L156)

2020-11-26 04:58 UTC, wjfwzzc commented on official/vision/detection/models/free_anchor.py
> +                gt_pred_prob[0, 0] = 0.001
经线下讨论：
1. 用if特判写两套逻辑，避免哨兵
2. cond_take的0-size tensor问题向engine组提issue解决

2020-12-08 11:24 UTC, wjfwzzc commented on official/vision/detection/README.md
> +| free-anchor-res101-coco-2x-800size  | 43.3         | 2             |
要么就都`free-anchor`，要么就都`freeanchor`
现在似乎是有些地方是前者（如这里和文件名），有些地方是后者（如weights和hub）

2020-12-08 11:52 UTC, FateScript commented on official/vision/detection/README.md
> +| free-anchor-res101-coco-2x-800size  | 43.3         | 2             |
已经统一成freeanchor了

2020-12-09 07:28 UTC, wjfwzzc commented on README.md
> +这些模型在COCO2017验证集上的测试结果如下：
是不是没有这个“如下”了？

2020-12-09 07:28 UTC, wjfwzzc approved these changes

2020-12-09 07:50 UTC, FateScript commented on README.md
> +这些模型在COCO2017验证集上的测试结果如下：
fixed.

2020-12-09 07:51 UTC, wjfwzzc commented
LGTM.

2020-12-09 07:51 UTC, merged