fix(classification): add default type in argparse
MegEngine/Models pull request #91
Opened 2021-01-28 11:33 UTC by zhouyizhuang-megvii

resolve #90

also fix a bug that Server would be unexpectedly recycled.

2021-01-28 11:42 UTC, FateScript requested changes

2021-01-28 11:42 UTC, FateScript commented on official/vision/classification/shufflenet/test.py
> +        server = dist.Server(port=args.dist_port)  # pylint: disable=unused-variable
server是一个没有用过的变量，flake8跪了

2021-01-28 11:42 UTC, FateScript commented on official/vision/classification/shufflenet/train.py
> +        server = dist.Server(port=args.dist_port)  # pylint: disable=unused-variable
ditto

2021-01-29 02:45 UTC, zhouyizhuang-megvii commented on official/vision/classification/shufflenet/test.py
> +        server = dist.Server(port=args.dist_port)  # pylint: disable=unused-variable
我disable了，我看到的怎么是

`official/nlp/bert/mrpc_dataset.py:12:0: E0401: Unable to import 'tokenization' (import-error)`

2021-01-29 06:26 UTC, FateScript approved these changes

2021-01-29 06:26 UTC, FateScript commented
LGTM.

2021-01-29 06:26 UTC, merged