chore(train): update training code, using dist.launcher
MegEngine/Models pull request #94
Opened 2021-04-08 11:24 UTC by Randolph87xxx

更新训练代码，替换成dist.launcher为启动方式
@wjfwzzc @zhouyizhuang-megvii 麻烦帮忙验证有没有问题

2021-04-08 11:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MegEngine/Models?pullRequest=94) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MegEngine/Models?pullRequest=94) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MegEngine/Models?pullRequest=94) it.</sub>

2021-06-01 10:31 UTC, MegChai commented
![2-months-later](https://user-images.githubusercontent.com/21091736/120309272-a1b34580-c307-11eb-810d-0d54a0ca73f9.jpeg)

2021-06-01 10:33 UTC, MegChai commented
> 更新训练代码，替换成dist.launcher为启动方式

建议补充说明一下为什么原来的写法不行（存在什么风险），还是说两者其实等效，装饰器更好看...

2021-06-02 03:11 UTC, zhouyizhuang-megvii requested changes
`world_size`的逻辑感觉不太对 FYI @wjfwzzc

2021-06-02 03:11 UTC, zhouyizhuang-megvii commented on official/vision/classification/resnet/test.py
> +    if args.world_size > 1:
`world_size`的逻辑不太对，指代的是机器数，所以DDP的真实`world_size = args.world_size * ngpus_per_node`

```python
if args.world_size * ngpus_per_node > 1:
    dist_worker(...)
else:
    worker(...)
```

2021-06-02 03:11 UTC, zhouyizhuang-megvii commented on official/vision/classification/resnet/test.py
> +        if args.world_size > 1:
ditto, 这里还是用`dist.get_world_size()`

2021-06-02 09:06 UTC, Randolph87xxx commented
> `world_size`的逻辑感觉不太对 FYI @wjfwzzc

已经将相关的word_size改成dist.get_world_size或者world_size*ngpus

(一开始还真没那么注意这个world_size不一样

2021-06-02 09:14 UTC, MegChai commented
> 亲测可以支持多机了。LGTM, but CI为什么挂了？

怀疑 GitHub 服务器遭受攻击

2021-06-02 09:17 UTC, MegChai commented
更具体的猜测：可能是 AWS 那边的集群服务被攻击了。

2021-06-02 09:19 UTC, MegChai commented
已经确定是 GitHub 问题：https://www.githubstatus.com/

> Update - We have discovered the source of the errors and have just rolled out a potential fix. We are now monitoring recovery and will update soon.
> Jun 2, 09:12 UTC

2021-06-02 12:11 UTC, Randolph87xxx commented
gently ping @wjfwzzc

2021-06-06 10:18 UTC, wjfwzzc commented
LGTM

2021-06-06 10:18 UTC, merged